### ISSUE TITLE
Consider registering test/implementation navigation functions

### ISSUE THREAD

**Issue by rranelli** [tonini/tester.el#1]
When I was implementing [maven-test-mode](https://github.com/rranelli/maven-test-mode) I ended up creating a simple and configurable test/implementation navigation.

The main Idea is that to go from the test file to the implementation file you apply a sequence of regex substitutions on the current file path.

Those substitutions are defined in a alist like this (for the case of common JUnit testing.):

``` elisp
(defcustom maven-test-class-to-test-subs
  '(("/src/main/" . "/src/test/")
    (".java" . "Test.java"))
"Patterns to substitute into class' filename to jump to the associated test."
:group 'maven-test)
```

From the quick look I had at `tester.el` it looks like it would be simple to register `alist`s to be used in the navigation utilities the same way that testing functions are registered.

**Comment by tonini** [comment]
Thanks for the feedback.

My intention with `tester` is not to serve this kind of functionality. It should be clean and simple, just the linux way. :-) 

But I will have a look at this for my `alchemist.el` package for sure. :+1: 

Cheers

**Comment by rranelli** [comment]
:+1: 

No problem. I find this kind of navigation one of the biggest productivity boosts I had with Emacs since I started using it. 
If you ever change your mind, lemme know.

Cheers.
